### ISSUE TITLE
xcode 8.3.2编译不通过

### ISSUE THREAD

**Issue by hug2008** [guange2015/ios-amr#2]
OXS 10.12
xcode 8.3.2
链接时通不过

**Comment by hug2008** [comment]
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by guange2015** [comment]
https://github.com/guange2015/ios-amr/tree/master/openamr
可以进这里跑下编译脚本

**Comment by guange2015** [comment]
9.2已通过
