### ISSUE TITLE
input wav file's AVSampleRateKey is 44100

### ISSUE THREAD

**Issue by westfort4July** [guange2015/ios-amr#3]
I change the `PCM_FRAME_SIZE` from 160 to 882 (0.02 * 44100), but it still not working. did I miss something? thanks in advance.

**Comment by guange2015** [comment]
可以一步步debug下，欢迎pull request

**Comment by guange2015** [comment]
今天翻看代码，发现EncodePCMToAMR有一处写死160了，已提交。
