### ISSUE TITLE
Android中设置outputFormat为Default时，iOS解码会失败

### ISSUE THREAD

**Issue by Juice007** [guange2015/ios-amr#4]
Android设置outputFormat为AMR_NB，iOS能正常解码并播放。但设置为Default，就无法正常播放。
因为在测试过程中发现，设置为NB的话，三星S8不支持，设置为Default就支持，但这样iOS又不支持。
有人遇到类似情况吗？怎么解决的呢

**Comment by guange2015** [comment]
可以考虑服务器支持下

**Comment by Juice007** [comment]
issue fixed！
首先Android端正确的做法是：
```
mRecorder.setOutputFormat(MediaRecorder.OutputFormat.AMR_NB);
mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);
```
这样能保证iOS和Android是互通的。
据Android同事调试后得出，Android必须将语音文件下载至本地播放就不会出现部分Android手机无法正常播放的问题了。
